//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueChestCounter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GoldBar {
            get {
                return ((float)(this["GoldBar"]));
            }
            set {
                this["GoldBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GoldBarPercentage {
            get {
                return ((float)(this["GoldBarPercentage"]));
            }
            set {
                this["GoldBarPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float BlueChest {
            get {
                return ((float)(this["BlueChest"]));
            }
            set {
                this["BlueChest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float BlueChestPercentage {
            get {
                return ((float)(this["BlueChestPercentage"]));
            }
            set {
                this["BlueChestPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float NoBlueChest {
            get {
                return ((float)(this["NoBlueChest"]));
            }
            set {
                this["NoBlueChest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CoronationRing {
            get {
                return ((float)(this["CoronationRing"]));
            }
            set {
                this["CoronationRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CoronationRingPercentage {
            get {
                return ((float)(this["CoronationRingPercentage"]));
            }
            set {
                this["CoronationRingPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LineageRing {
            get {
                return ((float)(this["LineageRing"]));
            }
            set {
                this["LineageRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LineageRingPercentage {
            get {
                return ((float)(this["LineageRingPercentage"]));
            }
            set {
                this["LineageRingPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float IntricacyRing {
            get {
                return ((float)(this["IntricacyRing"]));
            }
            set {
                this["IntricacyRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float IntricacyRingPercentage {
            get {
                return ((float)(this["IntricacyRingPercentage"]));
            }
            set {
                this["IntricacyRingPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float NoBlueChestCount {
            get {
                return ((float)(this["NoBlueChestCount"]));
            }
            set {
                this["NoBlueChestCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TodayTotalFight {
            get {
                return ((float)(this["TodayTotalFight"]));
            }
            set {
                this["TodayTotalFight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalFight {
            get {
                return ((float)(this["TotalFight"]));
            }
            set {
                this["TotalFight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GoldBarRecords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GoldBarRecords"]));
            }
            set {
                this["GoldBarRecords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalCoronationRing {
            get {
                return ((float)(this["TotalCoronationRing"]));
            }
            set {
                this["TotalCoronationRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalLineageRing {
            get {
                return ((float)(this["TotalLineageRing"]));
            }
            set {
                this["TotalLineageRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalIntricacyRing {
            get {
                return ((float)(this["TotalIntricacyRing"]));
            }
            set {
                this["TotalIntricacyRing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalGoldBar {
            get {
                return ((float)(this["TotalGoldBar"]));
            }
            set {
                this["TotalGoldBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalBlueChest {
            get {
                return ((float)(this["TotalBlueChest"]));
            }
            set {
                this["TotalBlueChest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastGoldBarDate {
            get {
                return ((string)(this["LastGoldBarDate"]));
            }
            set {
                this["LastGoldBarDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float OverallFight {
            get {
                return ((float)(this["OverallFight"]));
            }
            set {
                this["OverallFight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalCoronationRingP {
            get {
                return ((float)(this["TotalCoronationRingP"]));
            }
            set {
                this["TotalCoronationRingP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalLineageRingP {
            get {
                return ((float)(this["TotalLineageRingP"]));
            }
            set {
                this["TotalLineageRingP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalIntricacyRingP {
            get {
                return ((float)(this["TotalIntricacyRingP"]));
            }
            set {
                this["TotalIntricacyRingP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalGoldBarP {
            get {
                return ((float)(this["TotalGoldBarP"]));
            }
            set {
                this["TotalGoldBarP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TotalBlueChestP {
            get {
                return ((float)(this["TotalBlueChestP"]));
            }
            set {
                this["TotalBlueChestP"] = value;
            }
        }
    }
}
